name: vocotype_flutter
publish_to: "none"
description: Flutter frontend for VoCoType fcitx5 backend runtime.
version: 0.1.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  hotkey_manager: ^0.2.3
  tray_manager: ^0.5.1
  window_manager: ^0.5.1
  launch_at_startup: ^0.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

dependency_overrides:
  hotkey_manager_linux:
    path: third_party/hotkey_manager_linux
  tray_manager:
    path: third_party/tray_manager

flutter:
  uses-material-design: true
  assets:
    - assets/tray_icon.png
